/**
 * This class is generated by jOOQ
 */
package com.slc.persistence;


import com.slc.persistence.tables.Parameters;
import com.slc.persistence.tables.Roles;
import com.slc.persistence.tables.Users;
import com.slc.persistence.tables.records.ParametersRecord;
import com.slc.persistence.tables.records.RolesRecord;
import com.slc.persistence.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ParametersRecord> PARAMETERS_PKEY = UniqueKeys0.PARAMETERS_PKEY;
    public static final UniqueKey<RolesRecord> ROLES_PKEY = UniqueKeys0.ROLES_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UsersRecord, RolesRecord> USERS__FK_USERS_ROLES_IDX = ForeignKeys0.USERS__FK_USERS_ROLES_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ParametersRecord> PARAMETERS_PKEY = createUniqueKey(Parameters.PARAMETERS, "parameters_pkey", Parameters.PARAMETERS.NAME);
        public static final UniqueKey<RolesRecord> ROLES_PKEY = createUniqueKey(Roles.ROLES, "roles_pkey", Roles.ROLES.ROLE);
        public static final UniqueKey<UsersRecord> USERS_PKEY = createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<UsersRecord, RolesRecord> USERS__FK_USERS_ROLES_IDX = createForeignKey(com.slc.persistence.Keys.ROLES_PKEY, Users.USERS, "users__fk_users_roles_idx", Users.USERS.ROLE);
    }
}
