/**
 * This class is generated by jOOQ
 */
package com.slc.persistence;


import com.slc.persistence.tables.Parameters;
import com.slc.persistence.tables.Roles;
import com.slc.persistence.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.parameters</code>.
     */
    public static final Parameters PARAMETERS = com.slc.persistence.tables.Parameters.PARAMETERS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = com.slc.persistence.tables.Roles.ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.slc.persistence.tables.Users.USERS;
}
