/**
 * This class is generated by jOOQ
 */
package com.performancecarerx.persistence.tables.records;


import com.performancecarerx.persistence.tables.ExerciseStandards;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExerciseStandardsRecord extends TableRecordImpl<ExerciseStandardsRecord> implements Record5<Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = 145206896;

    /**
     * Setter for <code>public.exercise_standards.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.exercise_standards.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.exercise_standards.exercise_id</code>.
     */
    public void setExerciseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.exercise_standards.exercise_id</code>.
     */
    public Integer getExerciseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.exercise_standards.reps</code>.
     */
    public void setReps(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.exercise_standards.reps</code>.
     */
    public Integer getReps() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.exercise_standards.weight</code>.
     */
    public void setWeight(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.exercise_standards.weight</code>.
     */
    public Integer getWeight() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.exercise_standards.created_on_dttm</code>.
     */
    public void setCreatedOnDttm(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.exercise_standards.created_on_dttm</code>.
     */
    public Timestamp getCreatedOnDttm() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ExerciseStandards.EXERCISE_STANDARDS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ExerciseStandards.EXERCISE_STANDARDS.EXERCISE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ExerciseStandards.EXERCISE_STANDARDS.REPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ExerciseStandards.EXERCISE_STANDARDS.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ExerciseStandards.EXERCISE_STANDARDS.CREATED_ON_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getExerciseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getReps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedOnDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseStandardsRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseStandardsRecord value2(Integer value) {
        setExerciseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseStandardsRecord value3(Integer value) {
        setReps(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseStandardsRecord value4(Integer value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseStandardsRecord value5(Timestamp value) {
        setCreatedOnDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseStandardsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExerciseStandardsRecord
     */
    public ExerciseStandardsRecord() {
        super(ExerciseStandards.EXERCISE_STANDARDS);
    }

    /**
     * Create a detached, initialised ExerciseStandardsRecord
     */
    public ExerciseStandardsRecord(Integer userId, Integer exerciseId, Integer reps, Integer weight, Timestamp createdOnDttm) {
        super(ExerciseStandards.EXERCISE_STANDARDS);

        set(0, userId);
        set(1, exerciseId);
        set(2, reps);
        set(3, weight);
        set(4, createdOnDttm);
    }
}
