/**
 * This class is generated by jOOQ
 */
package com.performancecarerx.persistence.tables.records;


import com.performancecarerx.persistence.tables.ExercisesRecorded;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExercisesRecordedRecord extends UpdatableRecordImpl<ExercisesRecordedRecord> implements Record8<Long, Integer, Timestamp, Integer, Integer, Integer, Timestamp, String> {

    private static final long serialVersionUID = 383841950;

    /**
     * Setter for <code>public.exercises_recorded.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.exercises_recorded.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.exercises_recorded.exercise_id</code>.
     */
    public void setExerciseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.exercises_recorded.exercise_id</code>.
     */
    public Integer getExerciseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.exercises_recorded.recorded_dttm</code>.
     */
    public void setRecordedDttm(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.exercises_recorded.recorded_dttm</code>.
     */
    public Timestamp getRecordedDttm() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.exercises_recorded.weight</code>.
     */
    public void setWeight(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.exercises_recorded.weight</code>.
     */
    public Integer getWeight() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.exercises_recorded.reps</code>.
     */
    public void setReps(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.exercises_recorded.reps</code>.
     */
    public Integer getReps() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.exercises_recorded.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.exercises_recorded.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.exercises_recorded.created_dttm</code>.
     */
    public void setCreatedDttm(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.exercises_recorded.created_dttm</code>.
     */
    public Timestamp getCreatedDttm() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.exercises_recorded.note</code>.
     */
    public void setNote(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.exercises_recorded.note</code>.
     */
    public String getNote() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Integer, Timestamp, Integer, Integer, Integer, Timestamp, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Integer, Timestamp, Integer, Integer, Integer, Timestamp, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ExercisesRecorded.EXERCISES_RECORDED.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ExercisesRecorded.EXERCISES_RECORDED.EXERCISE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ExercisesRecorded.EXERCISES_RECORDED.RECORDED_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ExercisesRecorded.EXERCISES_RECORDED.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ExercisesRecorded.EXERCISES_RECORDED.REPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ExercisesRecorded.EXERCISES_RECORDED.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ExercisesRecorded.EXERCISES_RECORDED.CREATED_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ExercisesRecorded.EXERCISES_RECORDED.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getExerciseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getRecordedDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getReps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord value2(Integer value) {
        setExerciseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord value3(Timestamp value) {
        setRecordedDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord value4(Integer value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord value5(Integer value) {
        setReps(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord value7(Timestamp value) {
        setCreatedDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord value8(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExercisesRecordedRecord values(Long value1, Integer value2, Timestamp value3, Integer value4, Integer value5, Integer value6, Timestamp value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExercisesRecordedRecord
     */
    public ExercisesRecordedRecord() {
        super(ExercisesRecorded.EXERCISES_RECORDED);
    }

    /**
     * Create a detached, initialised ExercisesRecordedRecord
     */
    public ExercisesRecordedRecord(Long id, Integer exerciseId, Timestamp recordedDttm, Integer weight, Integer reps, Integer userId, Timestamp createdDttm, String note) {
        super(ExercisesRecorded.EXERCISES_RECORDED);

        set(0, id);
        set(1, exerciseId);
        set(2, recordedDttm);
        set(3, weight);
        set(4, reps);
        set(5, userId);
        set(6, createdDttm);
        set(7, note);
    }
}
