/**
 * This class is generated by jOOQ
 */
package com.performancecarerx.persistence.tables.records;


import com.performancecarerx.persistence.tables.ExerciseGoals;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExerciseGoalsRecord extends UpdatableRecordImpl<ExerciseGoalsRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -864142252;

    /**
     * Setter for <code>performancecarerx_db.exercise_goals.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>performancecarerx_db.exercise_goals.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>performancecarerx_db.exercise_goals.exercise_id</code>.
     */
    public void setExerciseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>performancecarerx_db.exercise_goals.exercise_id</code>.
     */
    public Integer getExerciseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>performancecarerx_db.exercise_goals.weight</code>.
     */
    public void setWeight(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>performancecarerx_db.exercise_goals.weight</code>.
     */
    public Integer getWeight() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>performancecarerx_db.exercise_goals.reps</code>.
     */
    public void setReps(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>performancecarerx_db.exercise_goals.reps</code>.
     */
    public Integer getReps() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>performancecarerx_db.exercise_goals.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>performancecarerx_db.exercise_goals.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>performancecarerx_db.exercise_goals.created_on_dttm</code>.
     */
    public void setCreatedOnDttm(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>performancecarerx_db.exercise_goals.created_on_dttm</code>.
     */
    public Timestamp getCreatedOnDttm() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ExerciseGoals.EXERCISE_GOALS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ExerciseGoals.EXERCISE_GOALS.EXERCISE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ExerciseGoals.EXERCISE_GOALS.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ExerciseGoals.EXERCISE_GOALS.REPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ExerciseGoals.EXERCISE_GOALS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ExerciseGoals.EXERCISE_GOALS.CREATED_ON_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getExerciseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getReps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedOnDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseGoalsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseGoalsRecord value2(Integer value) {
        setExerciseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseGoalsRecord value3(Integer value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseGoalsRecord value4(Integer value) {
        setReps(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseGoalsRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseGoalsRecord value6(Timestamp value) {
        setCreatedOnDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExerciseGoalsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExerciseGoalsRecord
     */
    public ExerciseGoalsRecord() {
        super(ExerciseGoals.EXERCISE_GOALS);
    }

    /**
     * Create a detached, initialised ExerciseGoalsRecord
     */
    public ExerciseGoalsRecord(Integer id, Integer exerciseId, Integer weight, Integer reps, Integer userId, Timestamp createdOnDttm) {
        super(ExerciseGoals.EXERCISE_GOALS);

        set(0, id);
        set(1, exerciseId);
        set(2, weight);
        set(3, reps);
        set(4, userId);
        set(5, createdOnDttm);
    }
}
