/**
 * This class is generated by jOOQ
 */
package com.performancecarerx.persistence;


import com.performancecarerx.persistence.tables.ExerciseGoals;
import com.performancecarerx.persistence.tables.ExerciseGroups;
import com.performancecarerx.persistence.tables.Exercises;
import com.performancecarerx.persistence.tables.ExercisesRecorded;
import com.performancecarerx.persistence.tables.RatioProfileValues;
import com.performancecarerx.persistence.tables.RatioProfiles;
import com.performancecarerx.persistence.tables.Roles;
import com.performancecarerx.persistence.tables.Users;
import com.performancecarerx.persistence.tables.records.ExerciseGoalsRecord;
import com.performancecarerx.persistence.tables.records.ExerciseGroupsRecord;
import com.performancecarerx.persistence.tables.records.ExercisesRecord;
import com.performancecarerx.persistence.tables.records.ExercisesRecordedRecord;
import com.performancecarerx.persistence.tables.records.RatioProfileValuesRecord;
import com.performancecarerx.persistence.tables.records.RatioProfilesRecord;
import com.performancecarerx.persistence.tables.records.RolesRecord;
import com.performancecarerx.persistence.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ExerciseGoalsRecord, Integer> IDENTITY_EXERCISE_GOALS = Identities0.IDENTITY_EXERCISE_GOALS;
    public static final Identity<ExercisesRecord, Integer> IDENTITY_EXERCISES = Identities0.IDENTITY_EXERCISES;
    public static final Identity<ExercisesRecordedRecord, Integer> IDENTITY_EXERCISES_RECORDED = Identities0.IDENTITY_EXERCISES_RECORDED;
    public static final Identity<RatioProfileValuesRecord, Integer> IDENTITY_RATIO_PROFILE_VALUES = Identities0.IDENTITY_RATIO_PROFILE_VALUES;
    public static final Identity<RatioProfilesRecord, Integer> IDENTITY_RATIO_PROFILES = Identities0.IDENTITY_RATIO_PROFILES;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ExerciseGoalsRecord> EXERCISE_GOALS_PKEY = UniqueKeys0.EXERCISE_GOALS_PKEY;
    public static final UniqueKey<ExerciseGroupsRecord> EXERCISE_GROUPS_PKEY = UniqueKeys0.EXERCISE_GROUPS_PKEY;
    public static final UniqueKey<ExercisesRecord> EXERCISES_PKEY = UniqueKeys0.EXERCISES_PKEY;
    public static final UniqueKey<ExercisesRecordedRecord> EXERCISES_RECORDED_PKEY = UniqueKeys0.EXERCISES_RECORDED_PKEY;
    public static final UniqueKey<RatioProfileValuesRecord> RATIO_PROFILE_VALUES_PKEY = UniqueKeys0.RATIO_PROFILE_VALUES_PKEY;
    public static final UniqueKey<RatioProfilesRecord> RATIO_PROFILES_PKEY = UniqueKeys0.RATIO_PROFILES_PKEY;
    public static final UniqueKey<RolesRecord> ROLES_PKEY = UniqueKeys0.ROLES_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ExerciseGoalsRecord, ExercisesRecord> EXERCISE_GOALS__FK_EXERCISE_GOALS_EXERCISE_IDX = ForeignKeys0.EXERCISE_GOALS__FK_EXERCISE_GOALS_EXERCISE_IDX;
    public static final ForeignKey<ExerciseGoalsRecord, UsersRecord> EXERCISE_GOALS__FK_EXERCISE_GOALS_USER_IDX = ForeignKeys0.EXERCISE_GOALS__FK_EXERCISE_GOALS_USER_IDX;
    public static final ForeignKey<ExercisesRecord, ExerciseGroupsRecord> EXERCISES__FK_EXERCISES_EXERCISE_GROUP_KEY_NAME_IDX = ForeignKeys0.EXERCISES__FK_EXERCISES_EXERCISE_GROUP_KEY_NAME_IDX;
    public static final ForeignKey<ExercisesRecord, RatioProfilesRecord> EXERCISES__FK_EXERCISES_RATIO_PROFILE_IDX = ForeignKeys0.EXERCISES__FK_EXERCISES_RATIO_PROFILE_IDX;
    public static final ForeignKey<ExercisesRecordedRecord, ExercisesRecord> EXERCISES_RECORDED__FK_EXERCISES_RECORDED_EXERCISES_IDX = ForeignKeys0.EXERCISES_RECORDED__FK_EXERCISES_RECORDED_EXERCISES_IDX;
    public static final ForeignKey<ExercisesRecordedRecord, UsersRecord> EXERCISES_RECORDED__FK_EXERCISES_RECORDED_USER_IDX = ForeignKeys0.EXERCISES_RECORDED__FK_EXERCISES_RECORDED_USER_IDX;
    public static final ForeignKey<RatioProfileValuesRecord, RatioProfilesRecord> RATIO_PROFILE_VALUES__FK_RATIO_PROFILE_VALUES_RATIO_PROFILE_IDX = ForeignKeys0.RATIO_PROFILE_VALUES__FK_RATIO_PROFILE_VALUES_RATIO_PROFILE_IDX;
    public static final ForeignKey<UsersRecord, RolesRecord> USERS__FK_USERS_ROLES_IDX = ForeignKeys0.USERS__FK_USERS_ROLES_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ExerciseGoalsRecord, Integer> IDENTITY_EXERCISE_GOALS = createIdentity(ExerciseGoals.EXERCISE_GOALS, ExerciseGoals.EXERCISE_GOALS.ID);
        public static Identity<ExercisesRecord, Integer> IDENTITY_EXERCISES = createIdentity(Exercises.EXERCISES, Exercises.EXERCISES.ID);
        public static Identity<ExercisesRecordedRecord, Integer> IDENTITY_EXERCISES_RECORDED = createIdentity(ExercisesRecorded.EXERCISES_RECORDED, ExercisesRecorded.EXERCISES_RECORDED.ID);
        public static Identity<RatioProfileValuesRecord, Integer> IDENTITY_RATIO_PROFILE_VALUES = createIdentity(RatioProfileValues.RATIO_PROFILE_VALUES, RatioProfileValues.RATIO_PROFILE_VALUES.ID);
        public static Identity<RatioProfilesRecord, Integer> IDENTITY_RATIO_PROFILES = createIdentity(RatioProfiles.RATIO_PROFILES, RatioProfiles.RATIO_PROFILES.ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ExerciseGoalsRecord> EXERCISE_GOALS_PKEY = createUniqueKey(ExerciseGoals.EXERCISE_GOALS, "exercise_goals_pkey", ExerciseGoals.EXERCISE_GOALS.ID);
        public static final UniqueKey<ExerciseGroupsRecord> EXERCISE_GROUPS_PKEY = createUniqueKey(ExerciseGroups.EXERCISE_GROUPS, "exercise_groups_pkey", ExerciseGroups.EXERCISE_GROUPS.KEY_NAME);
        public static final UniqueKey<ExercisesRecord> EXERCISES_PKEY = createUniqueKey(Exercises.EXERCISES, "exercises_pkey", Exercises.EXERCISES.ID);
        public static final UniqueKey<ExercisesRecordedRecord> EXERCISES_RECORDED_PKEY = createUniqueKey(ExercisesRecorded.EXERCISES_RECORDED, "exercises_recorded_pkey", ExercisesRecorded.EXERCISES_RECORDED.ID);
        public static final UniqueKey<RatioProfileValuesRecord> RATIO_PROFILE_VALUES_PKEY = createUniqueKey(RatioProfileValues.RATIO_PROFILE_VALUES, "ratio_profile_values_pkey", RatioProfileValues.RATIO_PROFILE_VALUES.ID);
        public static final UniqueKey<RatioProfilesRecord> RATIO_PROFILES_PKEY = createUniqueKey(RatioProfiles.RATIO_PROFILES, "ratio_profiles_pkey", RatioProfiles.RATIO_PROFILES.ID);
        public static final UniqueKey<RolesRecord> ROLES_PKEY = createUniqueKey(Roles.ROLES, "roles_pkey", Roles.ROLES.ROLE);
        public static final UniqueKey<UsersRecord> USERS_PKEY = createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ExerciseGoalsRecord, ExercisesRecord> EXERCISE_GOALS__FK_EXERCISE_GOALS_EXERCISE_IDX = createForeignKey(com.performancecarerx.persistence.Keys.EXERCISES_PKEY, ExerciseGoals.EXERCISE_GOALS, "exercise_goals__fk_exercise_goals_exercise_idx", ExerciseGoals.EXERCISE_GOALS.EXERCISE_ID);
        public static final ForeignKey<ExerciseGoalsRecord, UsersRecord> EXERCISE_GOALS__FK_EXERCISE_GOALS_USER_IDX = createForeignKey(com.performancecarerx.persistence.Keys.USERS_PKEY, ExerciseGoals.EXERCISE_GOALS, "exercise_goals__fk_exercise_goals_user_idx", ExerciseGoals.EXERCISE_GOALS.USER_ID);
        public static final ForeignKey<ExercisesRecord, ExerciseGroupsRecord> EXERCISES__FK_EXERCISES_EXERCISE_GROUP_KEY_NAME_IDX = createForeignKey(com.performancecarerx.persistence.Keys.EXERCISE_GROUPS_PKEY, Exercises.EXERCISES, "exercises__fk_exercises_exercise_group_key_name_idx", Exercises.EXERCISES.EXERCISE_GROUP_KEY_NAME);
        public static final ForeignKey<ExercisesRecord, RatioProfilesRecord> EXERCISES__FK_EXERCISES_RATIO_PROFILE_IDX = createForeignKey(com.performancecarerx.persistence.Keys.RATIO_PROFILES_PKEY, Exercises.EXERCISES, "exercises__fk_exercises_ratio_profile_idx", Exercises.EXERCISES.RATIO_PROFILE_ID);
        public static final ForeignKey<ExercisesRecordedRecord, ExercisesRecord> EXERCISES_RECORDED__FK_EXERCISES_RECORDED_EXERCISES_IDX = createForeignKey(com.performancecarerx.persistence.Keys.EXERCISES_PKEY, ExercisesRecorded.EXERCISES_RECORDED, "exercises_recorded__fk_exercises_recorded_exercises_idx", ExercisesRecorded.EXERCISES_RECORDED.EXERCISE_ID);
        public static final ForeignKey<ExercisesRecordedRecord, UsersRecord> EXERCISES_RECORDED__FK_EXERCISES_RECORDED_USER_IDX = createForeignKey(com.performancecarerx.persistence.Keys.USERS_PKEY, ExercisesRecorded.EXERCISES_RECORDED, "exercises_recorded__fk_exercises_recorded_user_idx", ExercisesRecorded.EXERCISES_RECORDED.USER_ID);
        public static final ForeignKey<RatioProfileValuesRecord, RatioProfilesRecord> RATIO_PROFILE_VALUES__FK_RATIO_PROFILE_VALUES_RATIO_PROFILE_IDX = createForeignKey(com.performancecarerx.persistence.Keys.RATIO_PROFILES_PKEY, RatioProfileValues.RATIO_PROFILE_VALUES, "ratio_profile_values__fk_ratio_profile_values_ratio_profile_idx", RatioProfileValues.RATIO_PROFILE_VALUES.RATIO_PROFILE_ID);
        public static final ForeignKey<UsersRecord, RolesRecord> USERS__FK_USERS_ROLES_IDX = createForeignKey(com.performancecarerx.persistence.Keys.ROLES_PKEY, Users.USERS, "users__fk_users_roles_idx", Users.USERS.ROLE);
    }
}
