/**
 * This class is generated by jOOQ
 */
package com.performancecarerx.persistence;


import com.performancecarerx.persistence.tables.ExerciseGoals;
import com.performancecarerx.persistence.tables.ExerciseGroups;
import com.performancecarerx.persistence.tables.Exercises;
import com.performancecarerx.persistence.tables.ExercisesRecorded;
import com.performancecarerx.persistence.tables.RatioProfileValues;
import com.performancecarerx.persistence.tables.RatioProfiles;
import com.performancecarerx.persistence.tables.Roles;
import com.performancecarerx.persistence.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PerformancecarerxDb extends SchemaImpl {

    private static final long serialVersionUID = 1679628538;

    /**
     * The reference instance of <code>performancecarerx_db</code>
     */
    public static final PerformancecarerxDb PERFORMANCECARERX_DB = new PerformancecarerxDb();

    /**
     * The table <code>performancecarerx_db.exercises</code>.
     */
    public final Exercises EXERCISES = com.performancecarerx.persistence.tables.Exercises.EXERCISES;

    /**
     * The table <code>performancecarerx_db.exercises_recorded</code>.
     */
    public final ExercisesRecorded EXERCISES_RECORDED = com.performancecarerx.persistence.tables.ExercisesRecorded.EXERCISES_RECORDED;

    /**
     * The table <code>performancecarerx_db.exercise_goals</code>.
     */
    public final ExerciseGoals EXERCISE_GOALS = com.performancecarerx.persistence.tables.ExerciseGoals.EXERCISE_GOALS;

    /**
     * The table <code>performancecarerx_db.exercise_groups</code>.
     */
    public final ExerciseGroups EXERCISE_GROUPS = com.performancecarerx.persistence.tables.ExerciseGroups.EXERCISE_GROUPS;

    /**
     * The table <code>performancecarerx_db.ratio_profiles</code>.
     */
    public final RatioProfiles RATIO_PROFILES = com.performancecarerx.persistence.tables.RatioProfiles.RATIO_PROFILES;

    /**
     * The table <code>performancecarerx_db.ratio_profile_values</code>.
     */
    public final RatioProfileValues RATIO_PROFILE_VALUES = com.performancecarerx.persistence.tables.RatioProfileValues.RATIO_PROFILE_VALUES;

    /**
     * The table <code>performancecarerx_db.roles</code>.
     */
    public final Roles ROLES = com.performancecarerx.persistence.tables.Roles.ROLES;

    /**
     * The table <code>performancecarerx_db.users</code>.
     */
    public final Users USERS = com.performancecarerx.persistence.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private PerformancecarerxDb() {
        super("performancecarerx_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Exercises.EXERCISES,
            ExercisesRecorded.EXERCISES_RECORDED,
            ExerciseGoals.EXERCISE_GOALS,
            ExerciseGroups.EXERCISE_GROUPS,
            RatioProfiles.RATIO_PROFILES,
            RatioProfileValues.RATIO_PROFILE_VALUES,
            Roles.ROLES,
            Users.USERS);
    }
}
