/**
 * This class is generated by jOOQ
 */
package com.performancecarerx.persistence;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.exercise_goals_id_seq</code>
     */
    public static final Sequence<Long> EXERCISE_GOALS_ID_SEQ = new SequenceImpl<Long>("exercise_goals_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.exercises_id_seq</code>
     */
    public static final Sequence<Long> EXERCISES_ID_SEQ = new SequenceImpl<Long>("exercises_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.exercises_recorded_id_seq</code>
     */
    public static final Sequence<Long> EXERCISES_RECORDED_ID_SEQ = new SequenceImpl<Long>("exercises_recorded_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.ratio_profile_values_id_seq</code>
     */
    public static final Sequence<Long> RATIO_PROFILE_VALUES_ID_SEQ = new SequenceImpl<Long>("ratio_profile_values_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.ratio_profiles_id_seq</code>
     */
    public static final Sequence<Long> RATIO_PROFILES_ID_SEQ = new SequenceImpl<Long>("ratio_profiles_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.users_id_seq</code>
     */
    public static final Sequence<Long> USERS_ID_SEQ = new SequenceImpl<Long>("users_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
