/**
 * This class is generated by jOOQ
 */
package com.performancecarerx.persistence;


import com.performancecarerx.persistence.tables.ExerciseGoals;
import com.performancecarerx.persistence.tables.ExerciseGroups;
import com.performancecarerx.persistence.tables.Exercises;
import com.performancecarerx.persistence.tables.ExercisesRecorded;
import com.performancecarerx.persistence.tables.Roles;
import com.performancecarerx.persistence.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in performancecarerx_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>performancecarerx_db.exercises</code>.
     */
    public static final Exercises EXERCISES = com.performancecarerx.persistence.tables.Exercises.EXERCISES;

    /**
     * The table <code>performancecarerx_db.exercises_recorded</code>.
     */
    public static final ExercisesRecorded EXERCISES_RECORDED = com.performancecarerx.persistence.tables.ExercisesRecorded.EXERCISES_RECORDED;

    /**
     * The table <code>performancecarerx_db.exercise_goals</code>.
     */
    public static final ExerciseGoals EXERCISE_GOALS = com.performancecarerx.persistence.tables.ExerciseGoals.EXERCISE_GOALS;

    /**
     * The table <code>performancecarerx_db.exercise_groups</code>.
     */
    public static final ExerciseGroups EXERCISE_GROUPS = com.performancecarerx.persistence.tables.ExerciseGroups.EXERCISE_GROUPS;

    /**
     * The table <code>performancecarerx_db.roles</code>.
     */
    public static final Roles ROLES = com.performancecarerx.persistence.tables.Roles.ROLES;

    /**
     * The table <code>performancecarerx_db.users</code>.
     */
    public static final Users USERS = com.performancecarerx.persistence.tables.Users.USERS;
}
