/**
 * This class is generated by jOOQ
 */
package com.performancecarerx.persistence.tables;


import com.performancecarerx.persistence.Keys;
import com.performancecarerx.persistence.Public;
import com.performancecarerx.persistence.tables.records.RatioProfilesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatioProfiles extends TableImpl<RatioProfilesRecord> {

    private static final long serialVersionUID = -1867097940;

    /**
     * The reference instance of <code>public.ratio_profiles</code>
     */
    public static final RatioProfiles RATIO_PROFILES = new RatioProfiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RatioProfilesRecord> getRecordType() {
        return RatioProfilesRecord.class;
    }

    /**
     * The column <code>public.ratio_profiles.id</code>.
     */
    public final TableField<RatioProfilesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('ratio_profiles_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.ratio_profiles.name</code>.
     */
    public final TableField<RatioProfilesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.ratio_profiles</code> table reference
     */
    public RatioProfiles() {
        this("ratio_profiles", null);
    }

    /**
     * Create an aliased <code>public.ratio_profiles</code> table reference
     */
    public RatioProfiles(String alias) {
        this(alias, RATIO_PROFILES);
    }

    private RatioProfiles(String alias, Table<RatioProfilesRecord> aliased) {
        this(alias, aliased, null);
    }

    private RatioProfiles(String alias, Table<RatioProfilesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RatioProfilesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RATIO_PROFILES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RatioProfilesRecord> getPrimaryKey() {
        return Keys.RATIO_PROFILES_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RatioProfilesRecord>> getKeys() {
        return Arrays.<UniqueKey<RatioProfilesRecord>>asList(Keys.RATIO_PROFILES_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatioProfiles as(String alias) {
        return new RatioProfiles(alias, this);
    }

    /**
     * Rename this table
     */
    public RatioProfiles rename(String name) {
        return new RatioProfiles(name, null);
    }
}
